import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { useState } from "react";
import { Download, FileText, Plus } from "lucide-react";

export default function Charter() {
  const { user } = useAuth();
  const { data: reports, isLoading, refetch } = trpc.charter.list.useQuery();
  const generateMutation = trpc.charter.generate.useMutation({
    onSuccess: () => { toast.success("Charter Council report generated successfully."); refetch(); },
    onError: (e) => toast.error(e.message),
  });
  const [period, setPeriod] = useState("2024-Q4");

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl font-bold text-foreground">Charter Council Reporting</h1>
          <p className="text-muted-foreground mt-2">Automated sectoral transformation reports for the <strong>Integrated Transport Sector B-BBEE Charter Council</strong>.</p>
        </div>
        {user?.role === "admin" && (
          <div className="flex items-center gap-2 flex-shrink-0">
            <input
              type="text"
              value={period}
              onChange={(e) => setPeriod(e.target.value)}
              placeholder="e.g. 2024-Q4"
              className="border border-border rounded-md px-3 py-2 text-sm w-28"
            />
            <Button
              size="sm"
              onClick={() => generateMutation.mutate({ reportingPeriod: period })}
              disabled={generateMutation.isPending}
            >
              <Plus className="w-4 h-4 mr-1" />
              Generate Report
            </Button>
          </div>
        )}
      </div>

      {/* Context */}
      <Card className="border shadow-sm bg-blue-50 border-blue-200">
        <CardContent className="p-5">
          <div className="flex items-start gap-3">
            <FileText className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-blue-800">
              <strong>Mandate:</strong> The Integrated Transport Sector B-BBEE Charter Council is responsible for monitoring and reporting on transformation within the transport sector. The Barometer platform generates automated reports providing the Charter Council with the research capacity it currently lacks, enabling it to fulfil its monitoring and reporting obligations under the Maritime Sector Code.
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Reports List */}
      {isLoading ? (
        <div className="space-y-3">{[...Array(3)].map((_, i) => <Skeleton key={i} className="h-24 w-full" />)}</div>
      ) : (reports ?? []).length === 0 ? (
        <div className="text-center py-16 text-muted-foreground">
          <FileText className="w-10 h-10 mx-auto mb-3 opacity-30" />
          <div className="font-medium">No charter council reports generated yet.</div>
          {user?.role === "admin" ? (
            <div className="text-sm mt-1">Use the "Generate Report" button above to create the first report.</div>
          ) : (
            <div className="text-sm mt-1">Reports will appear here once generated by an administrator.</div>
          )}
        </div>
      ) : (
        <div className="space-y-4">
          {(reports ?? []).map((r) => (
            <Card key={r.id} className="border shadow-sm">
              <CardHeader className="pb-2">
                <div className="flex items-start justify-between gap-3">
                  <CardTitle className="font-display text-base text-foreground">{r.title}</CardTitle>
                  <Badge variant="outline" className="text-xs flex-shrink-0">{r.reportingPeriod}</Badge>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
                  <div className="bg-muted/40 rounded-lg p-3 text-center">
                    <div className="text-xl font-bold font-display text-foreground">{r.totalEntities}</div>
                    <div className="text-xs text-muted-foreground">Total Entities</div>
                  </div>
                  <div className="bg-amber-50 rounded-lg p-3 text-center">
                    <div className="text-xl font-bold font-display text-amber-700">{r.emergingCount}</div>
                    <div className="text-xs text-amber-600">Emerging</div>
                  </div>
                  <div className="bg-blue-50 rounded-lg p-3 text-center">
                    <div className="text-xl font-bold font-display text-blue-700">{r.establishedCount}</div>
                    <div className="text-xs text-blue-600">Established</div>
                  </div>
                  <div className="bg-emerald-50 rounded-lg p-3 text-center">
                    <div className="text-xl font-bold font-display text-emerald-700">{r.leadingCount}</div>
                    <div className="text-xs text-emerald-600">Leading</div>
                  </div>
                </div>
                {r.summary && <p className="text-sm text-muted-foreground leading-relaxed">{r.summary}</p>}
                <div className="flex items-center justify-between mt-3">
                  <span className="text-xs text-muted-foreground">Generated {new Date(r.createdAt).toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" })}</span>
                  <Button variant="outline" size="sm" onClick={() => toast.info("PDF export coming soon.")}><Download className="w-3.5 h-3.5 mr-1" /> Export PDF</Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

